version: "3.3"

services:
  api:
    build: .
    ports:
    - 127.0.0.1:8000:80
    env_file:
      - .env

  db:
    image: postgres:latest
    container_name: fastapi_scraper
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
