version: "3.3"

services:
  api:
    container_name: fastapi_scraper_api
    build: .
    ports:
    - 8000:80
    volumes:
      - ./:/api
    restart: always
    image: api:latest
    depends_on:
      - db

  db:x
    container_name: fastapi_scraper_db
    image: postgres:latest
    env_file:
      - .env
    environment:
      - POSTGRES_DB:${POSTGRES_DB}
      - POSTGRES_USER:${POSTGRES_USER}
      - POSTGRES_PASSWORD:${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - scraper_data:/var/lib/postgresql/data

volumes:
  scraper_data: