"""Change url to download_url

Revision ID: 6a87ef81f8e5
Revises: 817fb48fa716
Create Date: 2023-10-31 12:03:27.078129

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6a87ef81f8e5'
down_revision: Union[str, None] = '817fb48fa716'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('download_tasks', sa.Column('download_url', sa.String(), nullable=False))
    op.drop_index('ix_download_tasks_url', table_name='download_tasks')
    op.create_index(op.f('ix_download_tasks_download_url'), 'download_tasks', ['download_url'], unique=False)
    op.drop_column('download_tasks', 'url')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('download_tasks', sa.Column('url', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_download_tasks_download_url'), table_name='download_tasks')
    op.create_index('ix_download_tasks_url', 'download_tasks', ['url'], unique=False)
    op.drop_column('download_tasks', 'download_url')
    # ### end Alembic commands ###
