"""Delete image model

Revision ID: 792fa4dc7c1f
Revises: 6a87ef81f8e5
Create Date: 2023-10-31 21:14:20.135264

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '792fa4dc7c1f'
down_revision: Union[str, None] = '6a87ef81f8e5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_images_download_task_id', table_name='images')
    op.drop_index('ix_images_filename', table_name='images')
    op.drop_index('ix_images_id', table_name='images')
    op.drop_table('images')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('images',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('filename', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('download_task_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['download_task_id'], ['download_tasks.id'], name='images_download_task_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='images_pkey')
    )
    op.create_index('ix_images_id', 'images', ['id'], unique=False)
    op.create_index('ix_images_filename', 'images', ['filename'], unique=False)
    op.create_index('ix_images_download_task_id', 'images', ['download_task_id'], unique=False)
    # ### end Alembic commands ###
