"""New Migration

Revision ID: 817fb48fa716
Revises: d3c22828586d
Create Date: 2023-10-30 21:05:58.869232

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '817fb48fa716'
down_revision: Union[str, None] = 'd3c22828586d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('download_tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('download_id', sa.String(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'DOWNLOADING', 'FINISHED', 'ERROR', name='downloadstatus'), nullable=True),
    sa.Column('progress', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_download_tasks_created_at'), 'download_tasks', ['created_at'], unique=False)
    op.create_index(op.f('ix_download_tasks_download_id'), 'download_tasks', ['download_id'], unique=True)
    op.create_index(op.f('ix_download_tasks_id'), 'download_tasks', ['id'], unique=False)
    op.create_index(op.f('ix_download_tasks_progress'), 'download_tasks', ['progress'], unique=False)
    op.create_index(op.f('ix_download_tasks_status'), 'download_tasks', ['status'], unique=False)
    op.create_index(op.f('ix_download_tasks_url'), 'download_tasks', ['url'], unique=False)
    op.create_table('images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(), nullable=False),
    sa.Column('download_task_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['download_task_id'], ['download_tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_images_download_task_id'), 'images', ['download_task_id'], unique=False)
    op.create_index(op.f('ix_images_filename'), 'images', ['filename'], unique=False)
    op.create_index(op.f('ix_images_id'), 'images', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_images_id'), table_name='images')
    op.drop_index(op.f('ix_images_filename'), table_name='images')
    op.drop_index(op.f('ix_images_download_task_id'), table_name='images')
    op.drop_table('images')
    op.drop_index(op.f('ix_download_tasks_url'), table_name='download_tasks')
    op.drop_index(op.f('ix_download_tasks_status'), table_name='download_tasks')
    op.drop_index(op.f('ix_download_tasks_progress'), table_name='download_tasks')
    op.drop_index(op.f('ix_download_tasks_id'), table_name='download_tasks')
    op.drop_index(op.f('ix_download_tasks_download_id'), table_name='download_tasks')
    op.drop_index(op.f('ix_download_tasks_created_at'), table_name='download_tasks')
    op.drop_table('download_tasks')
    # ### end Alembic commands ###
