name: Run Tests and Check Coverage

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run tests with coverage
        run: coverage run -m unittest discover tests

      - name: Generate coverage report
        run: coverage html

      - name: Check coverage
        run: |
          ACTUAL_COVERAGE=$(cat htmlcov/index.html | grep -o -E 'Total</span> [0-9]+\%' | cut -d' ' -f 2)
          echo "Coverage: $ACTUAL_COVERAGE"
          if [ "$ACTUAL_COVERAGE" -lt "55" ]; then
            echo "Coverage is below the required threshold (55%)"
            exit 1
          fi
